services:
  - type: web
    name: davay-landing-page
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_API_KEY
        sync: false
